### PR TITLE
add #ifndef's to headers

### PR DESCRIPTION
**Pull request by brentp**
this helps some downstream compilation (and is required for my nim wrapper).

### CODE REVIEW

**Comment by dpryan79** [comment]
Do nim and some other things need to import the headers multiple times?

**Comment by brentp** [comment]
I don't think they *need* to, but it happens. As you probably know better than I, guards like this are common practice, for example in htslib.

**Comment by dpryan79** [comment]
I'll tag a release real quick in case you need that.

**Comment by brentp** [comment]
thanks for merging! no release needed.

**Comment by dpryan79** [comment]
Good to know, I'll procrastinate then :)

**Pull request merged**
